#!/usr/bin/env bash
ARGS="$@"

DATA_FOLDER=`parse_argument $ARGS -D`

[[ ! -z "$DATA_FOLDER" ]] && chown postgres:postgres $DATA_FOLDER

su postgres -c "cd; $(find /usr -name initdb | head -n 1) $ARGS"
