#!/usr/bin/env bash
ARGS="$@"

TMP_FOLDER=`parse_argument $ARGS -k`

[[ ! -z "$TMP_FOLDER" ]] && chown postgres:postgres $TMP_FOLDER || echo "could not find temp folder... ignoring"

su postgres -c "cd; $(find /usr -name postgres | head -n 1) $ARGS"
